import type { PeoEntry } from "./types";

export const AIRFORCE_PEOS: PeoEntry[] = [
  {
    id: "pae-c3bm",
    name: "PAE C3BM",
    fullName: "Command, Control, Communications & Battle Management",
    parent: "AFLCMC",
    location: "Pentagon / Hanscom AFB, MA",
    budget: ">$1B",
    budgetNote: "ABMS ~$951M FY26; DAF Battle Network spans 50+ programs",
    categories: ["Battle management", "ABMS", "Data links", "C2", "JADC2", "Kill chains"],
    keyPrograms: [
      { name: "ABMS Digital Infrastructure", status: "Active deployment", budget: "~$951M FY26" },
      { name: "TOC-L", status: "MR2 (40+ systems)", budget: "Deployable C2 node" },
      { name: "CBC2", status: "Replaced legacy NORAD systems", budget: "CBC2+ in dev" },
      { name: "BACN", status: "Aerial relay operational", budget: "Comms bridging" },
      { name: "Kessel Run", status: "Agile software dev", budget: "Battle mgmt apps" },
    ],
    modernization: [
      "Deliver to depreciate — deploy now, improve iteratively",
      "Scale from experimentation to operational deployment",
      "Joint Fires Network integration (stood up Oct 2025)",
      "Kill chain alignment across 50+ programs",
      "Maritime Mission Integration (Nov 2025)",
    ],
    subOffices: [
      { office: "ABMS Division", name: "Advanced Battle Management System", desc: "Digital infrastructure; software; deployable C2" },
      { office: "Kessel Run", name: "Kessel Run Division", desc: "Agile software development" },
      { office: "C2ISR", name: "C2ISR Division", desc: "Command/control + ISR integration" },
      { office: "Aerial Networks", name: "Aerial Networks Division", desc: "BACN; Airborne Edge Node" },
      { office: "JFN", name: "Joint Fires Network", desc: "Integrated fires coordination (Oct 2025)" },
    ],
    leadership: [
      { name: "BG Jason Voorheis", title: "PAE (Feb 2026)" },
    ],
    budgetLinks: [
      { label: "AF FY2026 Budget", url: "https://www.saffm.hq.af.mil/FM-Resources/Budget/Air-Force-Presidents-Budget-FY26/" },
    ],
  },
  {
    id: "peo-acs",
    name: "PEO ACS",
    fullName: "Agile Combat Support",
    parent: "AFLCMC",
    location: "Hanscom AFB / Maxwell AFB / Wright-Patterson AFB",
    budget: "~$1.25B",
    budgetNote: "ES directorate ~$1.25B; GB directorate ~$1.25B",
    categories: ["Combat support", "Test systems", "Enterprise IT", "Logistics IT", "Force protection"],
    keyPrograms: [
      { name: "Automatic Test Systems (ATS)", status: "JTA modernization", budget: "Armament/avionics/EW" },
      { name: "LAIRCM", status: "Large aircraft IR countermeasures", budget: "Self-protection" },
      { name: "Enterprise Logistics Systems", status: "Modernization", budget: "Digital supply chain" },
      { name: "ACE Support Tools", status: "Agile Combat Employment", budget: "Support equipment" },
    ],
    modernization: [
      "Modernizing test systems toward common JTA",
      "LAIRCM and self-protection for high-value assets",
      "Agile Combat Employment support tools",
      "Enterprise logistics IT modernization",
    ],
    subOffices: [
      { office: "ES/HB", name: "Electronic Systems Directorate", desc: "120+ programs; ~$1.25B" },
      { office: "GB", name: "Business & Enterprise Systems", desc: "120+ programs; ~$1.25B" },
      { office: "RO", name: "Combat Readiness Directorate", desc: "ATS; EW; avionics; human systems" },
    ],
    leadership: [
      { name: "Lea Kirkwood, SES", title: "Director, ES" },
      { name: "Alvin Burse, SES", title: "Director, GB" },
    ],
    budgetLinks: [
      { label: "AF FY2026 Budget", url: "https://www.saffm.hq.af.mil/FM-Resources/Budget/Air-Force-Presidents-Budget-FY26/" },
    ],
  },
  {
    id: "peo-hn",
    name: "Cyber & Networks (HN)",
    fullName: "Cyber & Networks Directorate",
    parent: "AFLCMC",
    location: "Hanscom AFB, MA",
    budget: "Included in DAF IT",
    budgetNote: "AFNET operations; nuclear C3; crypto modernization",
    categories: ["Cyberspace", "Communications", "Cryptographic", "Nuclear C3", "AFNET"],
    keyPrograms: [
      { name: "AFNET", status: "Operations and modernization", budget: "Enterprise infrastructure" },
      { name: "Nuclear C3 Networks", status: "Modernization", budget: "NC3 support" },
      { name: "Cryptographic Modernization", status: "Ongoing", budget: "Crypto systems" },
      { name: "Airborne Communications", status: "Nodes operational", budget: "Partially under C3BM" },
    ],
    modernization: [
      "AFNET enterprise infrastructure modernization",
      "Nuclear C3 network resilience",
      "Cryptographic system upgrades",
      "Zero Trust implementation",
    ],
    subOffices: [
      { office: "Crypto & Cyber", name: "Crypto & Cyber Systems", desc: "Cryptographic systems; cybersecurity" },
      { office: "Enterprise IT", name: "Enterprise IT & Cyber Infrastructure", desc: "AFNET infrastructure" },
      { office: "Special Programs", name: "Cyber & Networks Special Programs", desc: "Classified programs" },
    ],
    leadership: [
      { name: "BG Joshua Williams", title: "Director (Jan 2026)" },
    ],
    budgetLinks: [],
  },
  {
    id: "peo-faa",
    name: "PEO FAA",
    fullName: "Fighters & Advanced Aircraft",
    parent: "AFLCMC / DRPM White",
    location: "Wright-Patterson AFB, OH",
    budget: "~$4.3B",
    budgetNote: "F-47 $3.5B + CCA $807M FY26",
    categories: ["Fighters", "6th-gen", "CCA drones", "F-35A", "F-22", "F-15EX", "Airborne C2"],
    keyPrograms: [
      { name: "F-47 NGAD", status: "Boeing awarded Mar 2025", budget: "$3.5B FY26" },
      { name: "CCA (Drone Wingmen)", status: "Prototypes flying FY25", budget: "$807M FY26" },
      { name: "F-35A Lightning II", status: "Block 4/TR-3 upgrades", budget: "24 aircraft FY26" },
      { name: "F-22A Raptor", status: "Upgrades ongoing", budget: "~$548M/yr avg" },
      { name: "F-15EX Eagle II", status: "Production", budget: "21 aircraft via reconciliation" },
      { name: "E-7 Wedgetail", status: "Effectively deferred/cancelled", budget: "~$200M FY26" },
    ],
    modernization: [
      "F-47 / CCA program execution (highest priority)",
      "CCA first flight and operational squadron",
      "F-35 Block 4 / TR-3 delivery",
      "F-22 sustainment as bridge to F-47",
      "SAOC development (NC3 airborne C2)",
    ],
    subOffices: [
      { office: "Advanced Aircraft", name: "Advanced Aircraft Division", desc: "F-47 NGAD; CCA" },
      { office: "F-22 Office", name: "F-22A Raptor Office", desc: "F-22 sustainment/upgrades" },
      { office: "F-15 FMS", name: "F-15 FMS", desc: "F-15 foreign military sales" },
      { office: "AWACS/Wedgetail", name: "AWACS & Wedgetail", desc: "E-3/E-7 battle management" },
      { office: "JSF/WJ", name: "Joint Strike Fighter", desc: "F-35 directorate (joint PEO)" },
      { office: "SAOC", name: "Survivable Airborne Ops Center", desc: "NC3 airborne command post" },
    ],
    leadership: [
      { name: "Col. Timothy Helfrich", title: "Director (Jan 2026)" },
    ],
    budgetLinks: [
      { label: "AF FY2026 Budget", url: "https://www.saffm.hq.af.mil/FM-Resources/Budget/Air-Force-Presidents-Budget-FY26/" },
    ],
  },
  {
    id: "peo-mobility",
    name: "PEO Mobility",
    fullName: "Mobility",
    parent: "AFLCMC",
    location: "Wright-Patterson AFB, OH",
    budget: "~$5B portfolio",
    budgetNote: "~$47B total portfolio value; KC-46 15/yr",
    categories: ["Airlift", "Tankers", "Strategic lift", "KC-46", "C-17", "C-130", "NGAL"],
    keyPrograms: [
      { name: "KC-46A Pegasus", status: "15/yr production", budget: "Multi-point refueling tanker" },
      { name: "C-17 Globemaster III", status: "222 aircraft; service through 2075", budget: "Strategic airlift backbone" },
      { name: "C-130 Hercules", status: "Ongoing upgrades", budget: "Tactical airlift" },
      { name: "C-5M Super Galaxy", status: "Drive to 55% MC rate", budget: "52 aircraft" },
      { name: "NGAL (Next-Gen Airlift)", status: "AoA FY2027; IOC 2041", budget: "Replaces C-5/C-17" },
    ],
    modernization: [
      "Connectivity: Starshield on tankers/C-17s",
      "Survivability: self-protection for tankers",
      "Resilient communications (counter-jamming, pLEO)",
      "NGAL industry concept exploration",
      "C-17 SLEP / C-5 Drive to 55",
    ],
    subOffices: [
      { office: "KC-46", name: "KC-46 Pegasus", desc: "Multi-point refueling tanker + cargo" },
      { office: "C-17", name: "C-17 Globemaster", desc: "Strategic airlift" },
      { office: "C-130", name: "C-130 Hercules", desc: "Tactical airlift" },
      { office: "C-5", name: "C-5 Galaxy", desc: "Heavy airlift; Drive to 55" },
      { office: "NGAL", name: "Next-Generation Airlift", desc: "Future C-5/C-17 replacement" },
    ],
    leadership: [
      { name: "Kevin D. Stamey, SES", title: "PEO/Director" },
    ],
    budgetLinks: [
      { label: "AF FY2026 Budget", url: "https://www.saffm.hq.af.mil/FM-Resources/Budget/Air-Force-Presidents-Budget-FY26/" },
    ],
  },
  {
    id: "peo-training",
    name: "PEO Training",
    fullName: "Training",
    parent: "AFLCMC",
    location: "Wright-Patterson AFB, OH",
    budget: "Included in ACS portfolio",
    budgetNote: "T-7A fielding; JSE expansion; 300+ programs",
    categories: ["Trainer aircraft", "Simulators", "JSE", "SCARS", "Flight training"],
    keyPrograms: [
      { name: "T-7A Red Hawk", status: "First delivery Dec 2025", budget: "Advanced pilot trainer" },
      { name: "JSE (Joint Simulation Environment)", status: "Multi-domain training", budget: "5th/6th-gen classified" },
      { name: "SCARS", status: "Virtualized OFP hosting", budget: "Simulator standards" },
      { name: "T-38 Talon", status: "Transitioning to T-7A", budget: "Legacy trainer" },
    ],
    modernization: [
      "T-7A Red Hawk fielding and GBTS",
      "JSE expansion to operational units",
      "SCARS for simulator concurrency",
      "Reduce flying hour dependency",
    ],
    subOffices: [
      { office: "T-7A Division", name: "T-7A Red Hawk", desc: "Advanced trainer aircraft" },
      { office: "Legacy Training", name: "Legacy Training Aircraft", desc: "T-38; T-6; T-1; T-53A" },
      { office: "ATC Division", name: "Advanced Training Capabilities", desc: "JSE; JSSE; SCARS" },
    ],
    leadership: [
      { name: "Rodney Stevens, SES", title: "PEO/Director" },
    ],
    budgetLinks: [],
  },
  {
    id: "peo-nuclear",
    name: "PEO Nuclear/Bombers",
    fullName: "Nuclear Deterrence & Bombers",
    parent: "AFLCMC / AFNWC / DRPM White",
    location: "Wright-Patterson AFB / Tinker AFB / Kirtland AFB",
    budget: "~$14.5B",
    budgetNote: "B-21 $10.3B; Sentinel $4.2B FY26",
    categories: ["Bombers", "ICBMs", "Nuclear cruise missiles", "B-21", "Sentinel", "B-52J"],
    keyPrograms: [
      { name: "B-21 Raider", status: "LRIP; 100+ planned", budget: "$10.3B FY26 total" },
      { name: "LGM-35A Sentinel", status: "Restructure; MS-B end 2026", budget: "$4.2B FY26" },
      { name: "AGM-181 LRSO", status: "Nuclear cruise missile", budget: "Doubled FY26 funding" },
      { name: "B-52J Modernization", status: "Engine replacement + radar", budget: "76 aircraft through 2050s+" },
      { name: "B-2 Spirit", status: "Wind-down (retire with B-21)", budget: "~$57M FY25" },
      { name: "B-1B Lancer", status: "Retirement by ~2030", budget: "Sustainment" },
    ],
    modernization: [
      "B-21 Raider LRIP and production expansion",
      "Sentinel ICBM restructure completion (2026)",
      "LRSO nuclear cruise missile development",
      "B-52J engine/radar/comms modernization",
      "B-2 and B-1B retirement management",
    ],
    subOffices: [
      { office: "RCO", name: "Rapid Capabilities Office", desc: "B-21 Raider program (Northrop Grumman)" },
      { office: "Bombers/WB", name: "Bombers Directorate", desc: "B-52J, B-2, B-1B sustainment" },
      { office: "AFNWC", name: "Nuclear Weapons Center", desc: "Sentinel; Minuteman III; LRSO; B61-12" },
      { office: "DRPM", name: "DRPM Critical Weapons", desc: "Gen. Dale White oversight" },
    ],
    leadership: [
      { name: "Gen. Dale R. White (4-star)", title: "DRPM Critical Weapons" },
    ],
    budgetLinks: [
      { label: "AF FY2026 Budget", url: "https://www.saffm.hq.af.mil/FM-Resources/Budget/Air-Force-Presidents-Budget-FY26/" },
    ],
  },
  {
    id: "usaf-rco",
    name: "USAF RCO",
    fullName: "Rapid Capabilities Office",
    parent: "SAF / DepSecDef",
    location: "Pentagon / Bolling AFB",
    budget: "~$10.3B (B-21)",
    budgetNote: "B-21: $4.7B RDT&E + $4.5B production + procurement",
    categories: ["Stealth bomber", "Classified capabilities", "Advanced prototypes"],
    keyPrograms: [
      { name: "B-21 Raider", status: "LRIP; 6 test aircraft", budget: "$692M avg unit cost" },
      { name: "F-47 NGAD (oversight)", status: "DRPM White", budget: "See PEO FAA" },
      { name: "Classified Programs", status: "Active", budget: "Not publicly disclosed" },
    ],
    modernization: [
      "B-21 production expansion (25% capacity increase)",
      "First operational aircraft target 2027 (Ellsworth AFB)",
      "Minimum 100 aircraft replacing B-1B and B-2",
    ],
    subOffices: [],
    leadership: [],
    budgetLinks: [
      { label: "B-21 Raider Fact Sheet", url: "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/2682973/b-21-raider/" },
    ],
  },
  {
    id: "peo-pea",
    name: "PEO PEA",
    fullName: "Presidential & Executive Airlift",
    parent: "AFLCMC",
    location: "Wright-Patterson AFB, OH",
    budget: "~$602M R&D FY26",
    budgetNote: "VC-25B delivery mid-2028; Qatar 747 bridge <$400M",
    categories: ["Presidential aircraft", "Executive transport", "VIP airlift", "Air Force One"],
    keyPrograms: [
      { name: "VC-25B (Air Force One)", status: "Delivery mid-2028", budget: ">$4.3B total" },
      { name: "Qatar 747 Bridge Aircraft", status: "L3Harris converting; summer 2026", budget: "<$400M" },
      { name: "C-32A / C-37 / C-40", status: "VP/Senior leader transport", budget: "Fleet sustainment" },
    ],
    modernization: [
      "VC-25B schedule recovery and delivery",
      "Qatar 747 bridge aircraft rapid fielding",
      "747-8 training pipeline establishment",
    ],
    subOffices: [],
    leadership: [
      { name: "BG Leigh Ottati", title: "Director/PEO" },
    ],
    budgetLinks: [
      { label: "AF FY2026 Budget", url: "https://www.saffm.hq.af.mil/FM-Resources/Budget/Air-Force-Presidents-Budget-FY26/" },
    ],
  },
  {
    id: "peo-tactical",
    name: "PEO Tactical/Armament",
    fullName: "Armament Directorate (PAE Air Dominance)",
    parent: "AFLCMC",
    location: "Eglin AFB, FL",
    budget: "~$4.2B",
    budgetNote: "JASSM-ER/LRASM surge; LRSO doubled; HACM development",
    categories: ["Weapons", "Munitions", "Electronic warfare", "Hypersonic", "Cruise missiles", "JASSM", "LRASM"],
    keyPrograms: [
      { name: "JASSM-ER", status: "Production surge", budget: "Major increase FY26" },
      { name: "LRASM", status: "Production doubled+", budget: "INDOPACOM priority" },
      { name: "AGM-181 LRSO", status: "Nuclear cruise missile", budget: "Doubled FY26" },
      { name: "HACM", status: "Air-breathing hypersonic", budget: "Raytheon/Northrop" },
      { name: "ARRW", status: "Relaunched FY26 budget", budget: "Boost-glide hypersonic" },
      { name: "SDB I & II", status: "Continued procurement", budget: "StormBreaker" },
    ],
    modernization: [
      "Modular open-system architecture for weapons",
      "Increased JASSM-ER/LRASM production capacity",
      "Hypersonic weapons development (HACM, ARRW)",
      "Long-range precision strike for INDOPACOM",
      "Affordability and mass production for peer competition",
    ],
    subOffices: [
      { office: "Long Range Systems", name: "Long Range Systems", desc: "LRSO; JASSM-ER; LRASM" },
      { office: "Air Dominance", name: "Air Dominance Division", desc: "Advanced air superiority weapons" },
      { office: "Attack", name: "Attack Division", desc: "Air-to-ground weapons" },
      { office: "Stand In Strike", name: "Stand In Strike", desc: "Close-in denied-area weapons" },
      { office: "Weapons Superiority", name: "Weapons Superiority", desc: "Electronic warfare; advanced weapons" },
    ],
    leadership: [
      { name: "BG Robert Lyons III", title: "Director/PEO" },
    ],
    budgetLinks: [
      { label: "AF FY2026 Budget", url: "https://www.saffm.hq.af.mil/FM-Resources/Budget/Air-Force-Presidents-Budget-FY26/" },
    ],
  },
  {
    id: "peo-isrsof",
    name: "PEO ISR & SOF",
    fullName: "ISR & Special Operations Forces",
    parent: "AFLCMC",
    location: "Wright-Patterson AFB, OH",
    budget: "~$2B",
    budgetNote: "HH-60W, MH-139A, ISR platform sustainment; 200+ programs",
    categories: ["ISR platforms", "SOF aircraft", "CSAR", "Helicopters", "RQ-4", "U-2", "A-10 retirement"],
    keyPrograms: [
      { name: "HH-60W Jolly Green II", status: "Production; replacing HH-60G", budget: "CSAR helicopter" },
      { name: "MH-139A Grey Wolf", status: "Production; ICBM security", budget: "Replacing UH-1N" },
      { name: "RQ-4 Global Hawk", status: "Block 40/50 sustained", budget: "Evaluating future" },
      { name: "U-2 Dragon Lady", status: "Sustained", budget: "Retirement debate" },
      { name: "A-10 Thunderbolt II", status: "All 162 retire by end 2027", budget: "CAS retirement" },
      { name: "HC-130J Combat King II", status: "In production", budget: "Personnel recovery" },
    ],
    modernization: [
      "HH-60W Jolly Green II fielding",
      "MH-139A Grey Wolf AFGSC integration",
      "ISR recapitalization (U-2 vs RQ-4)",
      "SOF aircraft sustainment",
      "A-10 retirement management",
    ],
    subOffices: [
      { office: "ISR Sensors", name: "ISR Sensors", desc: "RQ-4, U-2, SIGINT payloads" },
      { office: "SOF/PR", name: "SOF & Personnel Recovery", desc: "HC-130J; HH-60W; MC-130J" },
      { office: "Helo Office", name: "Helicopter Program Office", desc: "HH-60W; MH-139A" },
      { office: "CV-22", name: "CV-22 Osprey", desc: "SOF tiltrotor (NAS Pax River)" },
      { office: "645 AESG", name: "Big Safari", desc: "Rapid/special acquisition; classified" },
    ],
    leadership: [
      { name: "Col. John 'Moose' Dayton", title: "PEO/Director (Dec 2025)" },
    ],
    budgetLinks: [
      { label: "AF FY2026 Budget", url: "https://www.saffm.hq.af.mil/FM-Resources/Budget/Air-Force-Presidents-Budget-FY26/" },
    ],
  },
];
