import type { PeoEntry } from "./types";

export const ARMY_PEOS: PeoEntry[] = [
  {
    id: "peo-avn",
    name: "PEO Aviation",
    fullName: "Aviation (CPE Aviation)",
    parent: "PAE Maneuver Air",
    location: "Redstone Arsenal, AL",
    budget: "~$5-6B",
    budgetNote: "FLRAA ~$70B total program; $1.2B FY26 boost",
    categories: ["Helicopters", "Tiltrotor", "UAS", "Launched effects", "ISR", "Fixed wing"],
    keyPrograms: [
      { name: "FLRAA / MV-75 (V-280 Valor)", status: "Top priority; accelerated", budget: "~$70B total program" },
      { name: "AH-64E Apache V4", status: "Ongoing production", budget: "Attack helicopter" },
      { name: "UH-60M Black Hawk", status: "Modernization through 2050+", budget: "RFI issued Feb 2026" },
      { name: "CH-47F+ Chinook", status: "Block II fielding", budget: "Extended range" },
      { name: "HADES", status: "Rapid acquisition", budget: "6 aircraft target" },
      { name: "Launched Effects", status: "Active development", budget: "Air/ground launched" },
    ],
    modernization: [
      "FLRAA — #1 priority, accelerated",
      "Drone dominance — UAS marketplace, company-level drones",
      "Launched effects — ground and air-launched",
      "HADES high-altitude ISR",
      "UH-60M modernization through 2050+",
    ],
    subOffices: [
      { office: "PM FLRAA", name: "Future Long-Range Assault Aircraft", desc: "Bell V-280 Valor (MV-75)" },
      { office: "PM Apache", name: "Apache Attack Helicopters", desc: "AH-64E Guardian" },
      { office: "PM Utility", name: "Utility Helicopters", desc: "UH-60M Black Hawk; UH-60V" },
      { office: "PM Cargo", name: "Cargo Helicopters", desc: "CH-47F/F+ Chinook" },
      { office: "PM UAS", name: "Uncrewed Aircraft Systems", desc: "Gray Eagle; FTUAS; launched effects" },
      { office: "PM Fixed Wing", name: "Fixed Wing Aircraft", desc: "C-12; EMARSS; HADES" },
      { office: "PM AMSA", name: "Aviation Mission Systems", desc: "Avionics integration" },
      { office: "PM ITEP", name: "Improved Turbine Engine", desc: "Next-gen engine (uncertain)" },
    ],
    leadership: [
      { name: "BG David Phillips", title: "PEO" },
    ],
    budgetLinks: [
      { label: "Army Budget Materials", url: "https://www.asafm.army.mil/Budget-Materials/" },
    ],
  },
  {
    id: "peo-gcs",
    name: "PEO GCS",
    fullName: "Ground Combat Systems",
    parent: "PAE Maneuver Ground",
    location: "Detroit Arsenal, Warren, MI",
    budget: "~$3-4B",
    budgetNote: "M1E3 $723.5M FY26; XM30 ~$386M RDT&E FY26",
    categories: ["Armored vehicles", "Tanks", "Infantry fighting vehicles", "Self-propelled howitzer", "Robotic platforms"],
    keyPrograms: [
      { name: "M1E3 Abrams", status: "Early design; accelerated", budget: "$723.5M FY26" },
      { name: "XM30 MICV", status: "MS-B paused Feb 2026", budget: "~$386M RDT&E FY26" },
      { name: "M2A4E1 Bradley", status: "Sustainment + APS upgrade", budget: "Enduring until XM30" },
      { name: "AMPV (M113 replacement)", status: "Scaled back", budget: "Sustainment rates" },
      { name: "Stryker", status: "No new production", budget: "Sustainment only" },
    ],
    modernization: [
      "M1E3 next-gen tank (reduced weight, modular protection)",
      "XM30 as Bradley replacement (50mm, hybrid electric)",
      "Counter-UAS integration on all platforms",
      "360-degree situational awareness",
      "Digital/model-based systems engineering",
    ],
    subOffices: [
      { office: "PM MBTS", name: "Main Battle Tank Systems", desc: "M1A2 SEPv3, M1E3 development" },
      { office: "PM XM30", name: "XM30 Combat Vehicle", desc: "Bradley replacement" },
      { office: "PM MAV", name: "Mounted Armored Vehicles", desc: "AMPV variants" },
      { office: "PM Stryker", name: "Stryker BCT", desc: "Stryker sustainment" },
      { office: "PM SPHS", name: "Self-Propelled Howitzer", desc: "M109A7 Paladin (moving to PAE Fires)" },
    ],
    leadership: [],
    budgetLinks: [
      { label: "Army Budget Materials", url: "https://www.asafm.army.mil/Budget-Materials/" },
    ],
  },
  {
    id: "pae-fires",
    name: "PAE Fires",
    fullName: "Fires (formerly PEO Missiles & Space)",
    parent: "PAE Fires (top-level PAE)",
    location: "Redstone Arsenal, Huntsville, AL",
    budget: "~$4-5B",
    budgetNote: "LTAMDS $1.3B FY26; M-SHORAD $729M FY26; 62 programs of record",
    categories: ["Missiles", "Air defense", "Rockets", "HIMARS", "Hypersonic", "Counter-UAS", "LRPF"],
    keyPrograms: [
      { name: "Precision Strike Missile (PrSM)", status: "Production + Incr 4/5", budget: "Top LRPF priority" },
      { name: "HIMARS (M142)", status: "High rate; major FMS", budget: "Ongoing procurement" },
      { name: "LTAMDS", status: "Replaces Patriot radar", budget: "$1.3B FY26" },
      { name: "M-SHORAD (SGT STOUT)", status: "Stryker-based SHORAD", budget: "$729M FY26" },
      { name: "LRHW (Dark Eagle)", status: "Rapid development", budget: "Multiple batteries" },
      { name: "Typhon (Mid-Range)", status: "Deployed PHL/Europe", budget: "Tomahawk + SM-6" },
      { name: "IBCS", status: "Fielding to ADA battalions", budget: "Fires C2" },
    ],
    modernization: [
      "Long-range precision fires — Army #1 priority",
      "Strike moving land/maritime targets by 2027",
      "European/Indo-Pacific forward basing (Typhon)",
      "Accelerate M-SHORAD for counter-UAS",
      "LTAMDS to replace aging Patriot radar",
      "Directed energy integration into AMD layers",
    ],
    subOffices: [
      { office: "PM STORM", name: "Strategic & Operational Rockets", desc: "HIMARS; MLRS; ATACMS; PrSM" },
      { office: "PM SHIELD", name: "Short/Intermediate Effectors", desc: "Patriot; SHORAD; IFPC; interceptors" },
      { office: "PM STARE", name: "Search Track Acquire Radiate Eliminate", desc: "TPY-4; LTAMDS radars" },
      { office: "PM IFMC", name: "Integrated Fires Mission Command", desc: "IBCS; fires C2; sensor-shooter" },
      { office: "PM TAGM", name: "Tactical Aviation & Ground Munitions", desc: "Air/ground munitions" },
    ],
    leadership: [],
    budgetLinks: [
      { label: "PEO Missiles & Space", url: "https://www.army.mil/peoms" },
      { label: "Army Budget Materials", url: "https://www.asafm.army.mil/Budget-Materials/" },
    ],
  },
  {
    id: "peo-c3n",
    name: "PEO C3N",
    fullName: "Command, Control, Communications & Network",
    parent: "PAE Counter C2",
    location: "Aberdeen Proving Ground, MD",
    budget: "~$3B+",
    budgetNote: "NGC2 $2.9B FY26; HMS Radios $478M FY26",
    categories: ["Tactical networks", "C2", "Radios", "Cloud", "AI/ML", "Zero Trust"],
    keyPrograms: [
      { name: "NGC2 (Next Gen C2)", status: "OTA awards; 4th/25th ID prototypes", budget: "$2.9B FY26" },
      { name: "HMS Radios", status: "Ongoing procurement", budget: "$478M FY26" },
      { name: "Army Link 16", status: "Expanding", budget: "$134M FY26" },
      { name: "Capability Sets (CS23/25)", status: "Iterative fielding", budget: "Active" },
      { name: "NGLD-M (COMSEC)", status: "Replacing SKL", budget: "$66M FY25" },
    ],
    modernization: [
      "NGC2 — seamless, AI-enabled C2",
      "Data-centric architecture; cloud at tactical edge",
      "Transport-agnostic network",
      "Zero-trust cybersecurity",
      "Command post signature reduction",
      "DDIL operations capability",
    ],
    subOffices: [
      { office: "PM C2 Applications", name: "C2 Applications", desc: "Mission-focused apps; NGC2 ecosystem" },
      { office: "PM C2 Data/AI", name: "C2 Data/AI", desc: "AI/ML-enabled data platform; DDIL" },
      { office: "PM C2 Infrastructure", name: "C2 Infrastructure", desc: "Secure compute/store; crypto; cloud" },
      { office: "PM C2 Transport", name: "C2 Transport", desc: "Transport-agnostic radio network" },
      { office: "PM IEN", name: "Integrated Enterprise Network", desc: "Enterprise comms for Army/DoD" },
    ],
    leadership: [
      { name: "BG Jack 'Shane' Taylor", title: "CPE" },
    ],
    budgetLinks: [
      { label: "PEO C3N", url: "https://peoc3n.army.mil" },
      { label: "Army Budget Materials", url: "https://www.asafm.army.mil/Budget-Materials/" },
    ],
  },
  {
    id: "cpe-isw",
    name: "CPE IEW&S",
    fullName: "Intelligence, EW & Sensors (CPE ISW)",
    parent: "PAE Counter C2",
    location: "Aberdeen Proving Ground, MD",
    budget: "~$2.7B",
    budgetNote: "80+ programs of record; ~$1.5B PNT portfolio alone",
    categories: ["Intel", "Electronic warfare", "Cyber", "Sensors", "PNT", "Biometrics", "SIGINT"],
    keyPrograms: [
      { name: "TLS Manpack", status: "First unit issued FY24", budget: "SIGINT/EW at BCT" },
      { name: "TLS EAB", status: "First unit FY26", budget: "Division/Corps EW" },
      { name: "Prophet Enhanced", status: "ESP upgrades FY25-26", budget: "BCT SIGINT" },
      { name: "MAPS Gen II / DAPS", status: "Full rate production", budget: "M-code GPS" },
      { name: "Project Linchpin", status: "Army's first AI POR", budget: "AI-enabled ISR" },
      { name: "CREW Duke V3", status: "C-UAS loadset update", budget: "Counter-RCIED/C-UAS" },
    ],
    modernization: [
      "CEMA (Cyber-Electromagnetic Activities) integration",
      "AI/ML for SIGINT and EW signal recognition",
      "Miniaturized broadband EW antennas",
      "CMOSS architecture adoption",
      "Navigation warfare countermeasures",
      "Attritable/disaggregated EW payloads",
    ],
    subOffices: [
      { office: "PM EW&C", name: "Electronic Warfare & Cyber", desc: "EW; SIGINT; space; CREW" },
      { office: "PM C&S", name: "Cyber & Space", desc: "Offensive cyber; space layer" },
      { office: "PM DCO", name: "Defensive Cyber Operations", desc: "Defensive cyber tools" },
      { office: "PM IS&A", name: "Intel Systems & Analytics", desc: "ISR PED; Project Linchpin" },
      { office: "PM ASE", name: "Aircraft Survivability Equipment", desc: "IRCM; laser warning" },
      { office: "PM PNT", name: "Positioning, Navigation & Timing", desc: "MAPS; DAPS; M-code GPS" },
    ],
    leadership: [
      { name: "BG Kevin Chaney", title: "CPE ISW" },
    ],
    budgetLinks: [
      { label: "CPE ISW", url: "https://cpeisw.army.mil" },
      { label: "Army Budget Materials", url: "https://www.asafm.army.mil/Budget-Materials/" },
    ],
  },
  {
    id: "peo-soldier",
    name: "PEO Soldier",
    fullName: "Soldier",
    parent: "PAE Maneuver Ground",
    location: "Fort Belvoir, VA",
    budget: "~$1.5-2B",
    budgetNote: "NGSW; ENVG-B; SPS fielding",
    categories: ["Individual equipment", "Weapons", "Body armor", "Night vision", "Medical", "Crew-served weapons"],
    keyPrograms: [
      { name: "NGSW (XM7/XM250)", status: "Fielding", budget: "SIG Sauer / GD" },
      { name: "ENVG-B", status: "Fielding", budget: "L3Harris" },
      { name: "Soldier Protection System", status: "Fielding", budget: "Modular vest/helmet" },
      { name: "Air Warrior", status: "Ongoing", budget: "Aviation life support" },
      { name: "SBMC", status: "MTA Rapid Prototype", budget: "Dismounted C2/ISR" },
    ],
    modernization: [
      "Individual lethality overmatch (NGSW family)",
      "Soldier protection vs. evolving threats",
      "Dismounted SA (SBMC, ENVG, target designation)",
      "Soldier power management",
      "Medical capabilities for extended operations",
    ],
    subOffices: [
      { office: "PM SSV", name: "Soldier Survivability", desc: "Clothing, equipment, body armor, air warrior" },
      { office: "PM SL", name: "Soldier Lethality", desc: "Rifles, carbines, machine guns, NGSW" },
      { office: "PM SWAR", name: "Soldier Warrior", desc: "Sensors, targeting devices, SBMC" },
      { office: "PM SMD", name: "Soldier Medical Devices", desc: "Deployable medical capabilities" },
    ],
    leadership: [],
    budgetLinks: [
      { label: "PEO Soldier", url: "https://www.peosoldier.army.mil" },
    ],
  },
  {
    id: "peo-stri",
    name: "PEO STRI",
    fullName: "Simulation, Training & Instrumentation",
    parent: "PAE Counter C2",
    location: "Orlando, FL",
    budget: "~$800M-1B",
    budgetNote: "STE $73.8M; RVCT $96M FY25 procurement",
    categories: ["Training", "Simulation", "Live/virtual/constructive", "Cyber training", "Targets"],
    keyPrograms: [
      { name: "Synthetic Training Environment (STE)", status: "Active fielding", budget: "$73.8M FY25" },
      { name: "RVCT", status: "Contract through FY2039", budget: "$96M FY25" },
      { name: "PCTE", status: "Fielded", budget: "Cyber training platform" },
      { name: "Threat-UAS (T-UAS)", status: "Development", budget: "Drone threat training" },
    ],
    modernization: [
      "AI/ML integration into training environments",
      "3D gaming engine technologies",
      "Cloud-based synthetic training at tactical edge",
      "Drone/C-UAS training simulation",
      "Joint and coalition training interoperability",
    ],
    subOffices: [
      { office: "PM SE", name: "Synthetic Environment", desc: "STE; LVC architectures; game-engine training" },
      { office: "PM TRADE", name: "Training Devices", desc: "Live/virtual training; RVCT" },
      { office: "PM CT2", name: "Cyber, Test & Training", desc: "PCTE; cyber range" },
      { office: "PM ITTS", name: "Instrumentation, Targets & Threat Simulators", desc: "Range instrumentation; targets" },
    ],
    leadership: [
      { name: "BG Christine A. Beeler", title: "CPE STRI" },
    ],
    budgetLinks: [
      { label: "Army Budget Materials", url: "https://www.asafm.army.mil/Budget-Materials/" },
    ],
  },
  {
    id: "peo-enterprise",
    name: "PEO Enterprise",
    fullName: "Enterprise (CPE ES2)",
    parent: "Army CIO",
    location: "Fort Belvoir, VA",
    budget: "~$500-700M",
    budgetNote: "IPPS-A, EBS-C, GCSS-A, GFEBS",
    categories: ["Business IT", "ERP", "HR", "Logistics", "Finance", "Cloud"],
    keyPrograms: [
      { name: "IPPS-A", status: "Release 3 fielding", budget: "$5.3M FY26" },
      { name: "EBS-C (ERP Convergence)", status: "Converging 5 ERPs by ~2032", budget: "Major investment" },
      { name: "GCSS-A", status: "Sustainment", budget: "$1.99M FY26" },
      { name: "GFEBS", status: "Financial management", budget: "EBS-C portfolio" },
    ],
    modernization: [
      "IPPS-A full Army deployment",
      "EBS-C: converging 5 legacy ERPs",
      "Cloud-first enterprise services",
      "Data analytics platform modernization",
    ],
    subOffices: [
      { office: "PM IPPS-A", name: "Integrated Personnel & Pay", desc: "Personnel and force management" },
      { office: "PM EBS-C", name: "Enterprise Business Systems", desc: "Logistics/finance ERP convergence" },
      { office: "PM DIBS", name: "Defense Integrated Business Systems", desc: "Acquisition/training/readiness" },
      { office: "PM ES", name: "Enterprise Services", desc: "Cloud; data platform; IT services" },
    ],
    leadership: [
      { name: "Bill Hepworth", title: "PEO" },
    ],
    budgetLinks: [
      { label: "PEO Enterprise", url: "https://www.army.mil/enterprise" },
    ],
  },
  {
    id: "peo-cscss",
    name: "PEO CS&CSS",
    fullName: "Combat Support & Combat Service Support",
    parent: "PAE Agile Sustainment & Ammo",
    location: "Detroit Arsenal, Warren, MI",
    budget: "~$2.5-3B",
    budgetNote: "~$8.5B over 3 years (FY22-24); ~$2.8B/yr",
    categories: ["Tactical vehicles", "Energy", "Bridging", "Logistics", "Electric power", "Watercraft"],
    keyPrograms: [
      { name: "JLTV", status: "Production (slowed under ATI)", budget: "Joint Army/USMC/SOCOM" },
      { name: "FMTV / HEMTT", status: "Sustainment + upgrades", budget: "Medium tactical vehicles" },
      { name: "Common Tactical Truck (CTT)", status: "Development", budget: "Next-gen medium truck" },
      { name: "Bridging", status: "Active modernization", budget: "AVLB replacement" },
      { name: "Mobile Electric Power", status: "Next-gen generators", budget: "MEP-831A+" },
    ],
    modernization: [
      "Power and energy (hybrid vehicles, energy harvesting)",
      "Arctic/cold-weather logistics",
      "Predictive logistics / digital twin",
      "Robotic autonomous logistics vehicles",
      "Bridging modernization",
      "Advanced/additive manufacturing in the field",
    ],
    subOffices: [
      { office: "PM E2S2", name: "Expeditionary Energy & Sustainment", desc: "Power; generators; sustainment" },
      { office: "PM FP", name: "Force Projection", desc: "Bridging; engineer equipment; robotics" },
      { office: "JPO JLTV", name: "Joint Light Tactical Vehicle", desc: "JLTV; ground mobility" },
      { office: "PM TS", name: "Transportation Systems", desc: "Heavy/medium trucks; watercraft" },
    ],
    leadership: [
      { name: "BG Camilla White", title: "PEO" },
      { name: "Andrew DiMarco", title: "Deputy PEO" },
    ],
    budgetLinks: [
      { label: "PEO CS&CSS", url: "https://www.peocscss.army.mil" },
    ],
  },
  {
    id: "peo-acwa",
    name: "PEO ACWA",
    fullName: "Assembled Chemical Weapons Alternatives",
    parent: "Dedicated appropriation",
    location: "Aberdeen Proving Ground, MD",
    budget: "$213M FY26",
    budgetNote: "Major decline from $775M FY25; near end of mission",
    categories: ["Chemical weapons destruction", "Demilitarization", "CWC compliance"],
    keyPrograms: [
      { name: "PCAPP (Pueblo, CO)", status: "Demolition FY26", budget: "Mustard agent" },
      { name: "BGCAPP (Richmond, KY)", status: "Destruction complete; closure", budget: "GB/VX agents" },
      { name: "CSEPP Closeout", status: "Final closeout", budget: "Kentucky counties" },
    ],
    modernization: [
      "Program wind-down; complete by ~2028",
      "100% CWC obligation met",
      "Facility decommissioning and demolition",
    ],
    subOffices: [],
    leadership: [],
    budgetLinks: [
      { label: "Army Budget Materials", url: "https://www.asafm.army.mil/Budget-Materials/" },
    ],
  },
  {
    id: "jpeo-aa",
    name: "JPEO A&A",
    fullName: "Armaments & Ammunition",
    parent: "PAE Fires + PAE Agile Sustainment",
    location: "Picatinny Arsenal, NJ",
    budget: "~$3-4B",
    budgetNote: "Single Manager for Conventional Ammunition; $1.1B FY26 facility modernization",
    categories: ["Ammunition", "Armaments", "Artillery projectiles", "Rockets", "Small arms ammo", "Industrial base"],
    keyPrograms: [
      { name: "155mm Surge Production", status: "Active surge", budget: "Scranton/Radford plants" },
      { name: "HIMARS/MLRS Rockets", status: "Production acceleration", budget: "PL TAS" },
      { name: "Ammo Industrial Base", status: "21st-century by 2028", budget: "$1.1B FY26 facility mod" },
      { name: "Small Caliber Ammo", status: "Ongoing", budget: "PM MAS" },
    ],
    modernization: [
      "Ammunition stockpile replenishment (post-Ukraine priority)",
      "155mm artillery projectile production surge",
      "HIMARS/MLRS rocket production acceleration",
      "Organic industrial base modernization by 2028",
      "$1.1B FY26 for modernizing 7 ammo production facilities",
    ],
    subOffices: [
      { office: "PM CCS", name: "Close Combat Systems", desc: "Shoulder-launched; grenades; bombs" },
      { office: "PM CAS", name: "Combat Ammunition Systems", desc: "Artillery projectiles; tank ammo; mortar" },
      { office: "PM MAS", name: "Maneuver Ammunition Systems", desc: "Small caliber ammunition" },
      { office: "PL TAS", name: "Tactical Artillery Systems", desc: "Rocket/missile-class munitions" },
    ],
    leadership: [],
    budgetLinks: [
      { label: "JPEO A&A", url: "https://jpeoaa.army.mil" },
    ],
  },
];
