import type { PeoEntry } from "./types";

export const DEFENSEWIDE_PEOS: PeoEntry[] = [
  {
    id: "disa",
    name: "DISA",
    fullName: "Defense Information Systems Agency",
    parent: "DoD CIO",
    location: "Fort Meade, MD",
    budget: "~$3B+ O&M",
    budgetNote: "Seven mission areas; JWCC cloud; Zero Trust by FY2027",
    categories: ["DoDIN", "Enterprise IT", "Cloud", "Cyber", "Identity management", "DISN"],
    keyPrograms: [
      { name: "JWCC (Cloud)", status: "Multi-vendor operational", budget: "Enterprise cloud at all classification levels" },
      { name: "Zero Trust", status: "DoD-wide implementation", budget: "Full deployment by FY2027" },
      { name: "DoD365", status: "Enterprise license", budget: "Microsoft 365 for DoD" },
      { name: "DISN", status: "3,800 locations / 42 countries", budget: "$303M FY25" },
      { name: "ICAM", status: "Enterprise identity services", budget: "DoD-wide" },
    ],
    modernization: [
      "Zero Trust implementation across DoDIN",
      "JWCC cloud migration acceleration",
      "AI/data analytics integration",
      "Cyber warfighting architecture modernization",
      "5G/advanced communications for warfighter mobility",
    ],
    subOffices: [],
    leadership: [],
    budgetLinks: [
      { label: "DISA", url: "https://www.disa.mil" },
      { label: "DoD Budget Materials", url: "https://comptroller.defense.gov/Budget-Materials/" },
    ],
  },
  {
    id: "mda",
    name: "MDA",
    fullName: "Missile Defense Agency",
    parent: "USD(R&E)",
    location: "Pentagon / Huntsville, AL",
    budget: "$13.2B total",
    budgetNote: "$10.2B base + $3.0B reconciliation (Golden Dome); ~$10.5B RDT&E",
    categories: ["Missile defense", "GMD", "THAAD", "Aegis BMD", "Hypersonic defense", "Golden Dome"],
    keyPrograms: [
      { name: "GMD / NGI", status: "44 GBIs; NGI in development", budget: "~$3.2B" },
      { name: "THAAD", status: "37 interceptors FY26", budget: "~$1.6B" },
      { name: "Aegis BMD", status: "Network Enabled Interceptor", budget: "~$2.4B" },
      { name: "GPI (Glide Phase Interceptor)", status: "Hypersonic countermeasure", budget: "FOC ~2035" },
      { name: "Golden Dome ($25B total)", status: "National priority", budget: "$3B MDA share" },
      { name: "Defense of Guam", status: "Early planning", budget: "Comprehensive architecture" },
    ],
    modernization: [
      "Accelerate NGI fielding despite delays",
      "Establish 3rd GMD site (East Coast)",
      "Multi-layered defense of Guam",
      "Counter hypersonic weapons (GPI)",
      "Space-based sensing integration",
      "Expand THAAD batteries",
    ],
    subOffices: [],
    leadership: [],
    budgetLinks: [
      { label: "DoD Budget Materials", url: "https://comptroller.defense.gov/Budget-Materials/" },
      { label: "R-1 Document", url: "https://comptroller.war.gov/Portals/45/Documents/defbudget/FY2026/FY2026_r1.pdf" },
    ],
  },
  {
    id: "darpa",
    name: "DARPA",
    fullName: "Defense Advanced Research Projects Agency",
    parent: "USD(R&E)",
    location: "Arlington, VA",
    budget: "~$4.9B",
    budgetNote: "$4.5B base + $350M+ reconciliation; 12% increase",
    categories: ["R&D", "AI/ML", "Autonomy", "Biotechnology", "Quantum", "Hypersonics", "Microsystems"],
    keyPrograms: [
      { name: "Autonomous Systems", status: "Major investment ($13.4B DoD-wide)", budget: "TTO/STO" },
      { name: "AI/ML Programs", status: "CLARA; I2O-wide", budget: "Automated reasoning" },
      { name: "Quantum Technologies", status: "MTO/DSO", budget: "Research" },
      { name: "Biotechnology", status: "MASH; Smart-RBC", budget: "BTO programs" },
      { name: "Hypersonics Counter", status: "STO/TTO", budget: "Counter-adversary" },
    ],
    modernization: [
      "Create and prevent technological surprise",
      "Bridge fundamental science to military application",
      "Time-limited PM model (3-5 year tours)",
      "ERIS 7-minute pitch rapid awards",
    ],
    subOffices: [
      { office: "BTO", name: "Biological Technologies Office", desc: "Biology for national security; warfighter readiness" },
      { office: "DSO", name: "Defense Sciences Office", desc: "Quantum; novel materials; energy; physics" },
      { office: "I2O", name: "Information Innovation Office", desc: "AI/ML; cybersecurity; autonomous systems" },
      { office: "MTO", name: "Microsystems Technology Office", desc: "Photonic/quantum circuits; manufacturing" },
      { office: "STO", name: "Strategic Technology Office", desc: "Hypersonics; EW; distributed systems" },
      { office: "TTO", name: "Tactical Technology Office", desc: "Autonomous platforms; swarm tech; mass systems" },
    ],
    leadership: [],
    budgetLinks: [
      { label: "DARPA RDT&E Book", url: "https://comptroller.war.gov/Portals/45/Documents/defbudget/FY2026/budget_justification/pdfs/03_RDT_and_E/RDTE_Vol1_DARPA_MasterJustificationBook_PB_2026.pdf" },
    ],
  },
  {
    id: "socom-peos",
    name: "SOCOM PEOs",
    fullName: "US Special Operations Command Acquisition",
    parent: "USSOCOM SOF AT&L",
    location: "Tampa, FL (HQ)",
    budget: "$2.32B procurement",
    budgetNote: "$2.06B base + $263M reconciliation; $1.4B RDT&E",
    categories: ["SOF equipment", "Special mission aircraft", "Maritime SOF", "Rotary wing", "Digital apps"],
    keyPrograms: [
      { name: "OA-1K Skyraider II", status: "6 aircraft FY26", budget: "$156.6M" },
      { name: "AC-130J Ghostrider", status: "Sustained", budget: "SOF gunship" },
      { name: "MC-130J Talon III", status: "Fleet sustained", budget: "SOF transport" },
      { name: "Counter-UAS Systems", status: "FY26 priority", budget: "Robotic/counter-robotic" },
      { name: "SOF Ground Vehicles (FOSOV)", status: "Active", budget: "PM SOF Warrior" },
    ],
    modernization: [
      "Counter-UAS / robotic solutions (FY26 priority)",
      "Deep sensing in contested environments",
      "Assured access technologies",
      "Multidomain/great power conflict capabilities",
      "AI-enabled tactical edge decision-making",
    ],
    subOffices: [
      { office: "PEO-SW", name: "SOF Warrior", desc: "$1.5B annual; weapons, comms, protection" },
      { office: "PEO-FW", name: "Fixed Wing", desc: "MC-130J; OA-1K; AC-130J; U-28A; UAS" },
      { office: "PEO-RW", name: "Rotary Wing", desc: "MH-60; MH-47; 160th SOAR support" },
      { office: "PEO-M", name: "Maritime", desc: "NSW surface/undersea platforms" },
      { office: "PEO-SDA", name: "SOF Digital Applications", desc: "Software; data; DevSecOps" },
      { office: "PEO-SV", name: "Services", desc: "Professional/technical services" },
      { office: "PEO-SOFSA", name: "SOF Logistics & Support", desc: "Largest SOCOM service contract" },
      { office: "PEO-TIS", name: "Tactical Information Systems", desc: "Intel; tactical comms; SIGINT" },
    ],
    leadership: [],
    budgetLinks: [
      { label: "SOCOM Programs", url: "https://www.socom.mil/SOF-ATL/Pages/programs_new2.aspx" },
      { label: "SOCOM Procurement (P-1)", url: "https://comptroller.war.gov/Portals/45/Documents/defbudget/FY2026/budget_justification/pdfs/02_Procurement/PROC_SOCOM_PB_2026.pdf" },
    ],
  },
  {
    id: "cpe-cbrnd",
    name: "CPE CBRND",
    fullName: "CBRN Defense",
    parent: "PAE Layered Protection + CBRN",
    location: "Aberdeen Proving Ground, MD",
    budget: "~$1.2B",
    budgetNote: "CBRN defense portion of CBDP; slight decrease",
    categories: ["CBRN defense", "Protection", "Medical countermeasures", "Sensors", "Genomics", "SOF CBRN"],
    keyPrograms: [
      { name: "CBRN Protection Equipment", status: "70+ programs in sustainment", budget: "JPM Protection" },
      { name: "Medical Countermeasures", status: "MCM development", budget: "JPM Medical" },
      { name: "CBRN Sensors", status: "Lifecycle management", budget: "JPM Sensors" },
      { name: "JWARN", status: "Warning & Reporting Network", budget: "JPL Integration" },
      { name: "Genomic Sequencing", status: "Field capability", budget: "JPL Enabling Biotech" },
    ],
    modernization: [
      "Genomic sequencing workflows for field deployment",
      "Rapid MCM development and manufacturing",
      "CBRN defense in multi-domain/great power competition",
      "Integration with Army IBCS/IAMD",
    ],
    subOffices: [
      { office: "JPM Protection", name: "CBRN Protection", desc: "Individual/collective protection; 70+ programs" },
      { office: "JPM Medical", name: "CBRN Medical", desc: "Medical countermeasures; diagnostics" },
      { office: "JPM Sensors", name: "CBRN Sensors", desc: "Detection and identification systems" },
      { office: "JPM SOF", name: "CBRN SOF", desc: "SOF/Special Purpose Force equipment" },
      { office: "JPL Biotech", name: "Enabling Biotechnologies", desc: "Genomics; rapid MCM manufacturing" },
    ],
    leadership: [],
    budgetLinks: [
      { label: "CPE CBRND", url: "https://www.jpeocbrnd.osd.mil" },
    ],
  },
  {
    id: "dha-peos",
    name: "DHA PEOs",
    fullName: "Defense Health Agency",
    parent: "DHA",
    location: "Falls Church, VA",
    budget: "~$40B DHP",
    budgetNote: "DHP O&M ~$40B; MHS GENESIS fully deployed; JOMIS active",
    categories: ["Military healthcare IT", "Electronic health records", "Battlefield medicine", "Health surveillance"],
    keyPrograms: [
      { name: "MHS GENESIS", status: "Full deployment complete FY24", budget: "Oracle/Cerner EHR" },
      { name: "JOMIS", status: "Active development", budget: "$7.4M+/yr; +$11.3M FY26" },
      { name: "DMIX / EIDS", status: "Data analytics platform", budget: "Precision medicine" },
      { name: "MTF Direct Care", status: "+$310M investment FY26", budget: "Workforce expansion" },
    ],
    modernization: [
      "MHS GENESIS sustainment and data utilization",
      "JOMIS battlefield medicine integration",
      "Zero Trust for healthcare systems",
      "Cryopreservation Demonstration Program (FY26 new start)",
    ],
    subOffices: [
      { office: "PEO-DHMS", name: "Defense Healthcare Management Systems", desc: "MHS GENESIS; JOMIS; EIDS" },
      { office: "PEO Med Sys", name: "Medical Systems", desc: "Medical capital equipment; devices" },
    ],
    leadership: [],
    budgetLinks: [
      { label: "DHP Budget", url: "https://comptroller.war.gov/Portals/45/Documents/defbudget/FY2026/budget_justification/pdfs/09_Defense_Health_Program/00-DHP_Vols_I_and_II_PB26.pdf" },
    ],
  },
  {
    id: "dla",
    name: "DLA",
    fullName: "Defense Logistics Agency",
    parent: "USD(A&S)",
    location: "Fort Belvoir, VA",
    budget: "$401.5M O&M",
    budgetNote: "HQ/admin; total DLA enterprise much larger; 8,500+ suppliers",
    categories: ["Logistics", "Supply chain", "Energy", "Weapons support", "Distribution"],
    keyPrograms: [
      { name: "DAI (Financial Mgmt)", status: "120K+ users; 26 agencies", budget: "$97M FY26" },
      { name: "Warstoppers", status: "Industrial base surge", budget: "$49.3M FY26" },
      { name: "Supply Chain Digitization", status: "Advanced analytics", budget: "Active" },
      { name: "DLA Weapons Support", status: "+13% demand FY26", budget: "Parts and materials" },
    ],
    modernization: [
      "Supply chain digitization and demand forecasting",
      "Warstoppers industrial base surge capacity",
      "AI/automation for procurement efficiency",
      "Semiconductor strategic stockpiling through ~CY2030",
    ],
    subOffices: [],
    leadership: [],
    budgetLinks: [
      { label: "DLA O&M Budget", url: "https://comptroller.war.gov/Portals/45/Documents/defbudget/FY2026/budget_justification/pdfs/01_Operation_and_Maintenance/O_M_VOL_1_PART_1/DLA_OP-5.pdf" },
    ],
  },
];
