import type { PeoEntry } from "./types";

export const NAVY_PEOS: PeoEntry[] = [
  {
    id: "peo-iws",
    name: "PEO IWS",
    fullName: "Integrated Warfare Systems",
    parent: "NAVSEA",
    location: "Washington Navy Yard, D.C.",
    budget: "~$6.7B",
    budgetNote: "FY2025 DDG-51 total + SPY-6; FY2026 DDG(X) R&D $133.5M",
    categories: ["Combat systems", "Radars (SPY-6)", "Missiles", "AEGIS", "Directed energy", "IAMD"],
    keyPrograms: [
      { name: "DDG-51 Flight III", status: "Production", budget: "~$5.0B (2 ships FY25)" },
      { name: "AN/SPY-6(V) Radar", status: "Production ramp", budget: "Funded across FYDP" },
      { name: "DDG(X) Next-Gen Destroyer", status: "Concept design", budget: "$133.5M R&D FY26" },
      { name: "CPS (Hypersonic)", status: "Integration on DDG-1000", budget: "Classified" },
      { name: "NIFC-CA", status: "Architecture", budget: "Included in IWS" },
      { name: "Aegis Ashore", status: "Operational (Romania/Poland)", budget: "Continued" },
    ],
    modernization: [
      "Aegis system upgrades to Baseline 9/10",
      "Flight III DDG-51 production ramp with SPY-6",
      "DDG(X) concept development",
      "CPS fielding on Zumwalt; future SSN integration",
      "Directed energy weapons under IWS 2.0",
      "NIFC-CA architecture modernization",
    ],
    subOffices: [
      { office: "IWS 1.0", name: "AEGIS Integrated Combat Systems", desc: "DDG-51/CG-47 combat system; SPY-1/SPY-6; Standard Missile integration" },
      { office: "IWS 1F", name: "Aegis Fleet Readiness", desc: "Fleet introduction and readiness for Aegis" },
      { office: "IWS 2.0", name: "Above Water Sensors & Lasers", desc: "AN/SPY-6 AMDR; lasers; EO/IR sensors" },
      { office: "IWS 3.0", name: "Surface Ship Weapons", desc: "MK 41 VLS; gun systems; SM-2/SM-3/SM-6; LRASM" },
      { office: "IWS 4.0", name: "International Programs & FMS", desc: "Aegis exports to Japan, Korea, Spain, Australia" },
      { office: "IWS 5.0", name: "Undersea Systems", desc: "Surface ship ASW systems; sonar; torpedoes" },
      { office: "IWS 6.0", name: "Command and Control", desc: "Ship combat management; C2 integration" },
      { office: "IWS 80", name: "Ship Self-Defense / LCS / Unmanned", desc: "SSDS; LCS combat management; unmanned integration" },
      { office: "IWS 9.0", name: "Zumwalt Combat System", desc: "DDG-1000 TSCE; CPS integration" },
      { office: "IWS 11.0", name: "Terminal Defense Systems", desc: "RAM; CIWS Phalanx; SeaRAM" },
      { office: "IWS 12.0", name: "NATO SEASPARROW", desc: "NSSMS surface missile system" },
      { office: "IWS X", name: "Next-Gen Integrated Combat Systems", desc: "Systems-of-Systems Engineering / Integrated Fire" },
    ],
    leadership: [
      { name: "RADM Thomas J. Dickinson", title: "PEO" },
      { name: "Ryan Moore", title: "Deputy PEO" },
      { name: "Van Hendrey", title: "Executive Director" },
    ],
    budgetLinks: [
      { label: "Navy FY2026 Budget", url: "https://www.secnav.navy.mil/fmc/fmb/Pages/Fiscal-Year-2026.aspx" },
      { label: "DoD Budget Materials", url: "https://comptroller.defense.gov/Budget-Materials/" },
    ],
  },
  {
    id: "peo-usc",
    name: "PEO USC",
    fullName: "Unmanned & Small Combatants",
    parent: "NAVSEA",
    location: "Washington Navy Yard, D.C.",
    budget: "~$3B+",
    budgetNote: "FFG-62 ~$1.2B/ship; FY25 reconciliation adds $4.6B for UxV",
    categories: ["Frigates", "Unmanned surface vessels", "Mine warfare", "Unmanned undersea", "Expeditionary", "Naval Special Warfare"],
    keyPrograms: [
      { name: "FFG-62 Constellation Frigate", status: "Production (delayed ~36 mo)", budget: "~$1.2B/ship" },
      { name: "LUSV", status: "R&D; transition to PEO RAS", budget: "$54M R&D FY25" },
      { name: "MUSV", status: "R&D", budget: "$1.8B reconciliation" },
      { name: "Orca XLUUV", status: "Test/Eval", budget: "$21M R&D + $1.3B reconciliation" },
      { name: "Medium Landing Ship (LSM)", status: "First ship funded", budget: "$268M FY25" },
      { name: "LCS Sustainment", status: "35 hulls; early retirements", budget: "Sustainment" },
    ],
    modernization: [
      "Frigate program schedule recovery (FFG-62)",
      "Unmanned vessel demonstration and PEO RAS transition",
      "XLUUV/Orca production decision",
      "LSM fleet build-up for Marine Corps EABO",
      "Mine warfare modernization",
      "NSW systems modernization",
    ],
    subOffices: [
      { office: "PMS 406", name: "Unmanned Maritime Systems", desc: "LUSV, MUSV, XLUUV/Orca" },
      { office: "PMS 408", name: "Expeditionary Missions", desc: "EPF, LSM, connectors" },
      { office: "PMS 420", name: "LCS Mission Modules", desc: "MCM, SUW, ASW packages" },
      { office: "PMS 495", name: "Mine Warfare Systems", desc: "Mine countermeasures and hunting" },
      { office: "PMS 501", name: "LCS Ships", desc: "Freedom and Independence-class sustainment" },
      { office: "PMS 515", name: "FFG-62 Constellation", desc: "Guided-missile frigate program" },
      { office: "PMS 340", name: "Naval Special Warfare", desc: "SEAL delivery; combat submersibles" },
      { office: "PMS 300", name: "Boats & Craft", desc: "Small boats, craft, FMS" },
      { office: "PMS 525", name: "International USC", desc: "FMS for USC programs" },
    ],
    leadership: [
      { name: "Melissa L. Kirkendall", title: "Acting PEO / Executive Director" },
    ],
    budgetLinks: [
      { label: "Navy FY2026 Budget", url: "https://www.secnav.navy.mil/fmc/fmb/Pages/Fiscal-Year-2026.aspx" },
    ],
  },
  {
    id: "peo-ships",
    name: "PEO Ships",
    fullName: "Ships",
    parent: "NAVSEA",
    location: "Washington Navy Yard, D.C.",
    budget: "~$10B+ (SCN share)",
    budgetNote: "DDG-51 ~$6.7B total FY25; LPD ~$1.8B; DDG(X) $133.5M R&D FY26",
    categories: ["Surface combatants", "Amphibious ships", "Sealift", "Destroyers", "Polar cutter"],
    keyPrograms: [
      { name: "DDG-51 Arleigh Burke", status: "~94 ships; 2/yr production", budget: "~$6.7B FY25 total" },
      { name: "DDG(X) Next-Gen Destroyer", status: "Concept/design", budget: "$133.5M R&D FY26" },
      { name: "LPD-17 Flight II", status: "Production", budget: "~$1.8B/ship" },
      { name: "LHA America-class", status: "Production", budget: "$3.7B reconciliation" },
      { name: "DDG-1000 Zumwalt", status: "CPS integration", budget: "3 ships total" },
      { name: "Polar Security Cutter", status: "Under construction", budget: "Bollinger Shipyards" },
    ],
    modernization: [
      "DDG-51 Flight III production ramp with SPY-6",
      "DDG(X) concept design and requirements finalization",
      "Amphibious recapitalization (LPD Flight II, LHA-9)",
      "Polar Security Cutter delivery",
      "Surface combatant industrial base health",
      "T-AOL development",
    ],
    subOffices: [
      { office: "PMS 400D", name: "DDG-51 Arleigh Burke", desc: "Flight I/II/IIA/III build and sustainment" },
      { office: "PMS 460", name: "DDG(X)", desc: "Next-generation guided-missile destroyer" },
      { office: "PMS 500", name: "DDG-1000 Zumwalt", desc: "Three Zumwalt-class DDGs; CPS integration" },
      { office: "PMS 317", name: "Amphibious Assault / LPD-17", desc: "San Antonio-class amphibious ships" },
      { office: "PMS 377", name: "Amphibious Warfare (LHA)", desc: "America-class; LCAC; LCU; connectors" },
      { office: "PMS 373", name: "Polar Security Cutter", desc: "Heavy icebreaker program" },
      { office: "PMS 385", name: "Strategic & Theater Sealift", desc: "T-AKE, T-AOE, sealift vessels" },
      { office: "PMS 320", name: "Electric Ships Office", desc: "IPS development; DDG(X) power systems" },
      { office: "PMS 325", name: "Support Ships", desc: "Auxiliary and special mission ships" },
    ],
    leadership: [
      { name: "RADM Brian A. Metcalf", title: "PEO" },
      { name: "Jill J. Boward", title: "Executive Director, Combatants" },
    ],
    budgetLinks: [
      { label: "Navy FY2026 Budget", url: "https://www.secnav.navy.mil/fmc/fmb/Pages/Fiscal-Year-2026.aspx" },
    ],
  },
  {
    id: "peo-ssn",
    name: "PEO SSN",
    fullName: "Attack Submarines",
    parent: "NAVSEA / Team Submarine",
    location: "Washington Navy Yard, D.C.",
    budget: "~$7.6B",
    budgetNote: "FY25 Virginia total (hull + SIB); SIB FYDP $11.1B",
    categories: ["Attack submarines", "Weapons", "Sensors", "Submarine industrial base", "AUKUS"],
    keyPrograms: [
      { name: "Virginia-class SSN", status: "Production (1 FY25, 2/yr FY26)", budget: "~$7.6B FY25 total" },
      { name: "SSN(X) Next-Gen Attack Sub", status: "Concept development", budget: "R&D re-phased" },
      { name: "AUKUS Optimal Pathway", status: "Active", budget: "SIB investment" },
      { name: "MK48 ADCAP Torpedo", status: "Continued production", budget: "PMS 404" },
      { name: "BYG-1 Weapons Control", status: "Block upgrades ongoing", budget: "PMS 425" },
      { name: "Submarine Industrial Base", status: "$11.1B FYDP investment", budget: "$3.9B FY25" },
    ],
    modernization: [
      "Virginia-class rate recovery to 2/year by FY2026",
      "AUKUS SSN Optimal Pathway execution",
      "SIB expansion (~25 outsource nodes)",
      "SSN(X) requirements development",
      "BYG-1 upgrades for Project Overmatch",
      "CPS undersea-launch integration (FY2028)",
    ],
    subOffices: [
      { office: "PMS 450", name: "Virginia Class", desc: "SSN-774 new construction; Block V/VI" },
      { office: "PMS 392", name: "In-Service Submarines", desc: "688/21/22/774 support" },
      { office: "PMS 401", name: "Submarine Acoustic Systems", desc: "Sonar systems and sensors" },
      { office: "PMS 404", name: "Undersea Weapons", desc: "MK48 ADCAP torpedoes" },
      { office: "PMS 425", name: "Submarine Combat & Weapons Control", desc: "AN/BYG-1; fire control" },
      { office: "PMS 435", name: "Submarine Electromagnetic Systems", desc: "EW; periscopes; photonics masts" },
      { office: "PMS 415", name: "Undersea Defensive Warfare", desc: "Countermeasures; decoys" },
      { office: "PMS 394", name: "Advanced Undersea Systems", desc: "R&D; prototypes" },
      { office: "PMS 485", name: "Maritime Surveillance Systems", desc: "Fixed/mobile ocean surveillance; SOSUS" },
    ],
    leadership: [
      { name: "RADM Jonathan E. Rucker", title: "PEO" },
      { name: "Lisa M. Radocha", title: "Executive Director" },
    ],
    budgetLinks: [
      { label: "Navy FY2026 Budget", url: "https://www.secnav.navy.mil/fmc/fmb/Pages/Fiscal-Year-2026.aspx" },
    ],
  },
  {
    id: "peo-ssbn",
    name: "PEO SSBN",
    fullName: "Strategic Submarines",
    parent: "NAVSEA / Team Submarine",
    location: "Washington Navy Yard, D.C.",
    budget: "~$9.9B",
    budgetNote: "SSBN 827 incremental; NSBDF $5.9B FY25",
    categories: ["Ballistic missile submarines", "Nuclear deterrence", "Columbia-class", "Common Missile Compartment"],
    keyPrograms: [
      { name: "Columbia-class SSBN", status: "Construction (12 planned)", budget: "$9.9B FY25 (hull 2)" },
      { name: "Common Missile Compartment", status: "Joint w/ UK Dreadnought", budget: "Included" },
      { name: "Ohio-to-Columbia transition", status: "Active planning", budget: "NSBDF funded" },
    ],
    modernization: [
      "Columbia-class on-schedule production (first patrol FY2031)",
      "Ohio-class to Columbia transition",
      "CMC construction and installation",
      "D5LE re-hosting onto Columbia platforms",
      "Shore infrastructure at Kings Bay and Bangor",
    ],
    subOffices: [
      { office: "PMS 397", name: "Columbia-Class SSBN", desc: "Lead SSBN 826/827 and follow-on boats" },
    ],
    leadership: [
      { name: "RADM Todd S. Weeks", title: "PEO" },
      { name: "Matthew D. Sermon", title: "Executive Director" },
    ],
    budgetLinks: [
      { label: "Navy FY2026 Budget", url: "https://www.secnav.navy.mil/fmc/fmb/Pages/Fiscal-Year-2026.aspx" },
    ],
  },
  {
    id: "peo-uws",
    name: "PEO UWS",
    fullName: "Undersea Warfare Systems",
    parent: "NAVSEA / Team Submarine",
    location: "Washington Navy Yard, D.C.",
    budget: "Classified",
    budgetNote: "Submarine combat systems portfolio",
    categories: ["Submarine combat systems", "Project Overmatch", "Cybersecurity", "SWFTS"],
    keyPrograms: [
      { name: "Project Overmatch", status: "Active development", budget: "Classified" },
      { name: "SWFTS Software", status: "Upgrades ongoing", budget: "Included" },
      { name: "Advanced Undersea Payloads", status: "Development", budget: "PMS 394" },
    ],
    modernization: [
      "Project Overmatch submarine combat system data fabric",
      "SWFTS software upgrades",
      "Advanced undersea payload development",
      "Cybersecurity hardening of submarine combat systems",
    ],
    subOffices: [
      { office: "PMS 394", name: "Advanced Undersea Systems", desc: "Prototype undersea vehicles and payloads" },
      { office: "SUB-SB", name: "SWFTS", desc: "Software-defined combat system integration" },
      { office: "UDPIO", name: "Undersea Domain Program Integration", desc: "Cross-PEO undersea integration" },
    ],
    leadership: [
      { name: "RADM Douglas J. Adams", title: "PEO" },
    ],
    budgetLinks: [],
  },
  {
    id: "peo-cvn",
    name: "PEO CVN",
    fullName: "Aircraft Carriers",
    parent: "NAVSEA",
    location: "Washington Navy Yard, D.C.",
    budget: "~$12.7-13.3B per ship",
    budgetNote: "Ford-class total cost per ship; CVN-80/81 block buy savings ~$2.9B",
    categories: ["Carrier construction", "Carrier sustainment", "EMALS", "AAG", "Ford-class"],
    keyPrograms: [
      { name: "CVN-78 Gerald R. Ford", status: "Commissioned; IOC Dec 2021", budget: "~$13.3B total" },
      { name: "CVN-79 John F. Kennedy", status: "Delivery Jul 2025", budget: "~$12.7B" },
      { name: "CVN-80 Enterprise", status: "Under construction", budget: "~$12.8B" },
      { name: "CVN-81 Doris Miller", status: "Construction start 2026", budget: "~$12.9B" },
      { name: "CVN-75 Truman RCOH", status: "Funded FY2025", budget: "Included" },
    ],
    modernization: [
      "CVN-79 delivery and commissioning (FY2025)",
      "CVN-80 construction at Newport News",
      "Advanced planning for CVN-81 and CVN-82",
      "Ford-class EMALS/AAG reliability improvements",
      "Reducing CVN 50-year O&S costs (~$4B savings vs Nimitz)",
    ],
    subOffices: [
      { office: "PMS 378", name: "CVN New Construction", desc: "Ford-class construction" },
      { office: "PMS 379", name: "CVN-79/80/81", desc: "JFK, Enterprise, Doris Miller" },
      { office: "PMS 312", name: "In-Service Aircraft Carriers", desc: "RCOH; maintenance" },
      { office: "PMS 368", name: "Carrier Inactivation & Disposal", desc: "Decommissioning" },
      { office: "CPA", name: "Carrier Planning Activity", desc: "CVN-82 acquisition strategy" },
    ],
    leadership: [
      { name: "RADM Casey J. Moton", title: "PEO" },
      { name: "Justin T. Meyer", title: "Executive Director" },
    ],
    budgetLinks: [
      { label: "Navy FY2026 Budget", url: "https://www.secnav.navy.mil/fmc/fmb/Pages/Fiscal-Year-2026.aspx" },
    ],
  },
  {
    id: "peo-a",
    name: "PEO(A)",
    fullName: "ASW, Assault & Special Mission Programs",
    parent: "NAVAIR",
    location: "NAS Patuxent River, MD",
    budget: "~$3B+",
    budgetNote: "CH-53K ~$1.85B (19 ac FY25); P-8A sustainment",
    categories: ["Helicopters", "Maritime patrol", "Special mission", "ASW aviation", "Presidential helicopter"],
    keyPrograms: [
      { name: "CH-53K King Stallion", status: "Block buy production", budget: "~$1.85B (19 aircraft)" },
      { name: "P-8A Poseidon", status: "120+ aircraft; international", budget: "Sustainment/upgrades" },
      { name: "MQ-4C Triton", status: "Multi-INT delivered", budget: "Continued production" },
      { name: "MH-60R/S Seahawk", status: "Primary Navy helicopter", budget: "International sales" },
      { name: "VH-92A Presidential Helo", status: "In service", budget: "Completed" },
      { name: "E-6B / E-XX TACAMO", status: "E-XX in development", budget: "PMA-271" },
    ],
    modernization: [
      "CH-53K King Stallion block buy fielding",
      "P-8A international sustainment and upgrades",
      "MQ-4C Triton Multi-INT operational capability",
      "E-XX next-gen TACAMO development",
      "MH-60R/S international FMS expansion",
    ],
    subOffices: [
      { office: "PMA-261", name: "H-53 Heavy Lift", desc: "CH-53K King Stallion; CH-53E" },
      { office: "PMA-290", name: "Maritime Patrol & Reconnaissance", desc: "P-8A Poseidon; MQ-4C; P-3C" },
      { office: "PMA-299", name: "H-60 Multi-Mission Helicopter", desc: "MH-60R/S Seahawk" },
      { office: "PMA-274", name: "Presidential Helicopters", desc: "VH-92A Marine One" },
      { office: "PMA-275", name: "V-22 Joint Program", desc: "MV-22B; CV-22B; CMV-22B" },
      { office: "PMA-276", name: "H-1 Program", desc: "UH-1Y Venom; AH-1Z Viper" },
      { office: "PMA-271", name: "TACAMO (E-6B/E-XX)", desc: "Airborne strategic C2" },
      { office: "PMA-264", name: "Air ASW Systems", desc: "ASW sensors; sonobuoys" },
      { office: "PMA-207", name: "Tactical Airlift", desc: "CMV-22B; C-2A sustainment" },
    ],
    leadership: [
      { name: "BGen David C. Walsh, USMC", title: "PEO" },
    ],
    budgetLinks: [
      { label: "Navy FY2026 Budget", url: "https://www.secnav.navy.mil/fmc/fmb/Pages/Fiscal-Year-2026.aspx" },
    ],
  },
  {
    id: "peo-t",
    name: "PEO(T)",
    fullName: "Tactical Aircraft Programs",
    parent: "NAVAIR",
    location: "NAS Patuxent River, MD",
    budget: "~$4B+",
    budgetNote: "F/A-18 sustainment; EA-18G/NGJ; F/A-XX $454M R&D FY25",
    categories: ["Fighters", "Electronic attack", "Airborne C2", "Training aircraft", "Air-to-air missiles", "EMALS/AAG"],
    keyPrograms: [
      { name: "F/A-18E/F Super Hornet", status: "Block III upgrades", budget: "Production winding down" },
      { name: "EA-18G / NGJ", status: "NGJ Mid-Band production", budget: "NGJ Low-Band in dev" },
      { name: "E-2D Advanced Hawkeye", status: "In production", budget: "CEC equipped" },
      { name: "F/A-XX (6th Gen Fighter)", status: "Development", budget: "$454M R&D + $500M reconciliation" },
      { name: "AIM-120D / AIM-260 JATM", status: "Procurement/Development", budget: "PMA-259" },
      { name: "EMALS / AAG", status: "Ford-class installed", budget: "Reliability improvements" },
    ],
    modernization: [
      "F/A-XX 6th-gen fighter development",
      "NGJ Mid-Band production acceleration",
      "E-2D Advanced Hawkeye CEC integration",
      "AIM-260 JATM development",
      "EMALS/AAG reliability improvements on Ford-class",
    ],
    subOffices: [
      { office: "PMA-265", name: "F/A-18 and EA-18G", desc: "Super Hornet and Growler" },
      { office: "PMA-234", name: "Airborne Electronic Attack", desc: "EA-18G; NGJ pods" },
      { office: "PMA-231", name: "E-2/C-2 Hawkeye", desc: "E-2D Advanced Hawkeye" },
      { office: "PMA-259", name: "Air-to-Air Missiles", desc: "AMRAAM; AIM-9X; AIM-260" },
      { office: "PMA-251", name: "Aircraft Launch & Recovery", desc: "EMALS; AAG" },
      { office: "PMA-209", name: "Air Combat Electronics", desc: "Avionics; EW suites" },
      { office: "PMA-205", name: "Training Systems & Ranges", desc: "T-45C; T-6; simulators" },
      { office: "PMA-226", name: "Adversary Aircraft", desc: "F-5 adversary services" },
    ],
    leadership: [
      { name: "RADM John S. Lemmon", title: "PEO" },
    ],
    budgetLinks: [
      { label: "Navy FY2026 Budget", url: "https://www.secnav.navy.mil/fmc/fmb/Pages/Fiscal-Year-2026.aspx" },
    ],
  },
  {
    id: "peo-uw",
    name: "PEO(U&W)",
    fullName: "Unmanned Aviation & Strike Weapons",
    parent: "NAVAIR",
    location: "NAS Patuxent River, MD",
    budget: "~$3B+",
    budgetNote: "MQ-25A + Tomahawk + LRASM + NSM procurement",
    categories: ["UAS", "Precision strike", "Carrier drone", "Tomahawk", "LRASM", "Targets"],
    keyPrograms: [
      { name: "MQ-25A Stingray", status: "3 aircraft FY25", budget: "Carrier tanker drone" },
      { name: "Tomahawk Block V/Va", status: "MYP; anti-ship variant", budget: "22 TLAM FY25" },
      { name: "LRASM", status: "Production", budget: "30 LRASM + 60 LRASM-ER FY25" },
      { name: "Naval Strike Missile", status: "Procurement", budget: "102 NSMs FY25" },
      { name: "MQ-4C Triton", status: "Multi-INT IOC", budget: "Continued" },
      { name: "Carrier UCAV", status: "RFP issued", budget: "$500M reconciliation" },
    ],
    modernization: [
      "MQ-25A Stingray carrier integration",
      "Tomahawk Block Va anti-ship capability",
      "LRASM production surge",
      "Carrier-based UCAV development (loyal wingman)",
      "MQ-4C Triton operational expansion",
    ],
    subOffices: [
      { office: "PMA-268", name: "Unmanned Carrier Aviation", desc: "MQ-25A Stingray; future UCAV" },
      { office: "PMA-280", name: "Tomahawk Weapons System", desc: "Block IV/V/Va" },
      { office: "PMA-201", name: "Precision Strike Weapons", desc: "JASSM-ER; LRASM; NSM; Harpoon" },
      { office: "PMA-262", name: "Persistent Maritime UAS", desc: "MQ-4C Triton" },
      { office: "PMA-266", name: "Multi-Mission Tactical UAS", desc: "MQ-8C Fire Scout" },
      { office: "PMA-242", name: "Direct & Time-Sensitive Strike", desc: "SDB II / StormBreaker" },
      { office: "PMA-263", name: "Small Tactical UAS", desc: "RQ-21A Blackjack" },
      { office: "PMA-208", name: "Aerial Targets", desc: "BQM-177A; supersonic targets" },
      { office: "PMA-281", name: "Strike Planning & Execution", desc: "JMPS; digital targeting" },
    ],
    leadership: [
      { name: "RADM Stephen R. Tedford", title: "PEO" },
    ],
    budgetLinks: [
      { label: "Navy FY2026 Budget", url: "https://www.secnav.navy.mil/fmc/fmb/Pages/Fiscal-Year-2026.aspx" },
    ],
  },
  {
    id: "peo-f35j",
    name: "PEO(F-35/J)",
    fullName: "Joint Strike Fighter",
    parent: "NAVAIR (Joint Program)",
    location: "Pentagon, Arlington, VA",
    budget: "~$3.4B (Navy/USMC share)",
    budgetNote: "26 F-35 total FY25 (13 F-35B + 9 F-35C + 4 F-35C USMC)",
    categories: ["5th-gen fighter", "F-35B STOVL", "F-35C carrier variant", "Block 4 upgrades"],
    keyPrograms: [
      { name: "F-35B (USMC)", status: "Production; 13 FY25", budget: "STOVL variant" },
      { name: "F-35C (Navy/USMC)", status: "Production; 13 FY25", budget: "Carrier variant" },
      { name: "Block 4 / TR-3", status: "Upgrade development", budget: "Avionics refresh" },
      { name: "Total DON Buy", status: "340 F-35C + 420 F-35B", budget: "760 aircraft planned" },
    ],
    modernization: [
      "Block 4 capability upgrades",
      "Technology Refresh 3 (TR-3) avionics",
      "F-35C carrier integration expansion",
      "International partner coordination",
    ],
    subOffices: [],
    leadership: [
      { name: "Lt Gen Michael J. Schmidt, USAF", title: "PEO (Joint)" },
    ],
    budgetLinks: [
      { label: "F-35 Program Office", url: "https://www.f35.com" },
    ],
  },
  {
    id: "peo-c4i",
    name: "PEO C4I",
    fullName: "Command, Control, Communications, Computers & Intelligence",
    parent: "NAVWAR",
    location: "San Diego, CA",
    budget: ">$5B FYDP",
    budgetNote: "PMW/A 170 alone >$5B FYDP; IT total ~$6.1B unclassified",
    categories: ["Communications", "Networks", "Cyber", "ISR", "C2", "SATCOM", "Project Overmatch"],
    keyPrograms: [
      { name: "CANES", status: ">110 ships", budget: "Primary ship network" },
      { name: "Navy Multiband Terminal (NMT)", status: "Production", budget: ">$5B FYDP" },
      { name: "NTCDL", status: "MS-C Oct 2024", budget: "IOC 2025" },
      { name: "Project Overmatch", status: "Active development", budget: "Data fabric" },
      { name: "GCCS-M", status: "Operational", budget: "PMW 150" },
      { name: "Crypto Modernization", status: "Ongoing", budget: "$86M FY25" },
    ],
    modernization: [
      "CANES proliferation and upgrades",
      "SATCOM resiliency (STtNG NGSO/PLEO diversity)",
      "Crypto modernization (cease-key dates for legacy)",
      "NMT production and international fielding",
      "Project Overmatch data fabric",
      "Zero Trust Architecture implementation",
    ],
    subOffices: [
      { office: "PMW/A 170", name: "Communications & GPS Navigation", desc: "SATCOM; NMT; NTCDL; CBSP; DMR; GPNTS" },
      { office: "PMW 160", name: "Tactical Networks", desc: "CANES; ADNS; SubLAN; EPCA" },
      { office: "PMW 150", name: "Naval C2 Systems", desc: "GCCS-M; NATO NILE; NC3" },
      { office: "PMW 130", name: "Cybersecurity", desc: "SHARKCAGE; CND; crypto modernization" },
      { office: "PMW 120", name: "Battlespace Awareness & IO", desc: "ISR integration; SEWIP; DCGS-N" },
      { office: "PMA/PMW 101", name: "MIDS / Link 16", desc: "Tactical data links" },
      { office: "PMW 750", name: "Carrier Air Integration", desc: "CVN C4I; amphib C4I" },
      { office: "PMW 760", name: "Ship Integration", desc: "New construction C4I" },
      { office: "PMW 770", name: "Undersea Communications", desc: "Submarine C4I; NC3; VLF/ELF" },
      { office: "PMW 790", name: "Shore & Expeditionary", desc: "DJC2; MOC; Navy Expeditionary C4I" },
      { office: "PMW 740", name: "International C4I", desc: "FMS C4I; security cooperation" },
    ],
    leadership: [
      { name: "Bill Luebke, Ph.D.", title: "PEO" },
      { name: "Capt. Khary Hembree-Bey", title: "Deputy Military PEO" },
    ],
    budgetLinks: [
      { label: "PEO C4I", url: "https://www.peoc4i.navy.mil" },
      { label: "Navy FY2026 Budget", url: "https://www.secnav.navy.mil/fmc/fmb/Pages/Fiscal-Year-2026.aspx" },
    ],
  },
  {
    id: "peo-digital",
    name: "PEO Digital",
    fullName: "Digital and Enterprise Services",
    parent: "NAVWAR",
    location: "San Diego, CA",
    budget: "~$6.1B (DON IT share)",
    budgetNote: "Navy ERP $616M; NGEN $73M; total DON unclassified IT ~$6.1B",
    categories: ["Enterprise IT", "Cloud", "Microsoft 365", "NMCI", "Zero Trust", "Navy ERP"],
    keyPrograms: [
      { name: "Flank Speed / M365", status: "650K+ users", budget: "Enterprise cloud" },
      { name: "NMCI / ONE-Net", status: "Transformation", budget: "$73M NGEN FY25" },
      { name: "Navy ERP", status: "SAP S/4 HANA migration", budget: "$616M FY25" },
      { name: "Flank Speed Wireless", status: "~15K users", budget: "Afloat expansion" },
      { name: "Naval Identity Services (NIS)", status: "Zero Trust IAM", budget: "Cross-DON" },
    ],
    modernization: [
      "Flank Speed adoption and mobile scaling",
      "NMCI/ONE-Net device transition to NAUS configs",
      "Zero Trust migration using NIS",
      "IoE pier connectivity expansion",
      "Data center consolidation (IL6 cloud)",
    ],
    subOffices: [],
    leadership: [
      { name: "Louis A. Koplon", title: "PEO" },
      { name: "Jeff Proudfoot", title: "Executive Director" },
    ],
    budgetLinks: [
      { label: "PEO Digital", url: "https://www.peodigital.navy.mil" },
    ],
  },
  {
    id: "peo-mlb",
    name: "PEO MLB",
    fullName: "Manpower, Logistics & Business Solutions",
    parent: "NAVWAR",
    location: "San Diego, CA",
    budget: "~$1B+",
    budgetNote: "Navy ERP $616M (shared); NP2 $164M; NMRO $211M",
    categories: ["HR IT", "Logistics IT", "Business systems", "Financial IT", "Marine Corps logistics"],
    keyPrograms: [
      { name: "Navy Personnel & Pay (NP2)", status: "Deployment", budget: "$164M FY25" },
      { name: "Navy ERP / ERP+", status: "SAP S/4 HANA transition", budget: "$616M FY25" },
      { name: "GCSS-MC", status: "Marine Corps logistics", budget: "Sustainment" },
      { name: "Naval MRO", status: "100% DME", budget: "$211M FY25" },
      { name: "LOG IT Modernization", status: "Reducing 200 legacy systems", budget: "Active" },
    ],
    modernization: [
      "NP2 deployment replacing legacy NSIPS/pay systems",
      "Navy ERP+ SAP S/4 HANA transition",
      "LOG IT digital transformation",
      "Agile/SAFe delivery model adoption",
      "AI/ML analytics for HR and logistics",
    ],
    subOffices: [],
    leadership: [
      { name: "Christine Rodriguez", title: "PEO" },
      { name: "Mary Thoms", title: "Executive Director" },
    ],
    budgetLinks: [
      { label: "PEO MLB", url: "https://www.peomlb.navy.mil" },
    ],
  },
  {
    id: "ssp",
    name: "SSP",
    fullName: "Strategic Systems Programs",
    parent: "Direct Reporting (DRPM)",
    location: "Washington Navy Yard, D.C.",
    budget: "Classified (NSBDF $5.9B FY25)",
    budgetNote: "D5LE2 +$400M; SLCM-N +$2B reconciliation; CPS classified",
    categories: ["Nuclear deterrence", "Trident", "Hypersonic strike", "SLBM", "SLCM-N", "CPS"],
    keyPrograms: [
      { name: "Trident D5LE", status: "Deployed on all Ohio SSBNs", budget: "Re-hosting to Columbia" },
      { name: "D5LE2", status: "SRR 2025; IOC 2039", budget: "$400M acceleration" },
      { name: "Columbia CMC", status: "Joint w/ UK Dreadnought", budget: "Launcher engineering" },
      { name: "CPS (Hypersonic)", status: "Zumwalt FY25/26; Virginia FY28", budget: ">$3.9B reconciliation" },
      { name: "SLCM-N", status: "Development restarted", budget: "$2B reconciliation" },
    ],
    modernization: [
      "Columbia-class CMC installation; D5LE re-hosting",
      "D5LE2 development (SRR 2025 milestone)",
      "CPS fielding on DDG-1000 and Virginia integration",
      "SLCM-N development acceleration",
      "Nuclear weapons surety modernization",
      "AUKUS technology transfer (UK SWS)",
    ],
    subOffices: [
      { office: "SP20X", name: "D5LE Strategic Weapons", desc: "Trident II D5 Life Extension" },
      { office: "SP21X", name: "D5LE2 Development", desc: "Next-gen SLBM" },
      { office: "SP22X", name: "Launcher Engineering / CMC", desc: "Common Missile Compartment" },
      { office: "CPS", name: "Conventional Prompt Strike", desc: "Hypersonic weapon program" },
      { office: "SLCM-N", name: "Nuclear Sea-Launched Cruise Missile", desc: "Nuclear SLCM development" },
    ],
    leadership: [
      { name: "VADM Johnny Wolfe", title: "Director, SSP" },
    ],
    budgetLinks: [
      { label: "SSP Website", url: "https://www.ssp.navy.mil" },
    ],
  },
];
