import type { PeoEntry } from "./types";

export const SPACEFORCE_PEOS: PeoEntry[] = [
  {
    id: "peo-aats",
    name: "PEO AATS",
    fullName: "Assured Access to Space",
    parent: "Space Systems Command (SSC)",
    location: "Los Angeles AFB (El Segundo), CA",
    budget: "~$1.4B",
    budgetNote: "NSSL Phase 3 $5.6B total; FY25 7 launches",
    categories: ["Launch services", "Launch infrastructure", "NSSL", "Eastern/Western Range"],
    keyPrograms: [
      { name: "NSSL Phase 3", status: "Multi-award $5.6B", budget: "Blue Origin/SpaceX/ULA" },
      { name: "Launch Infrastructure", status: "Modernization ongoing", budget: "Cape Canaveral + Vandenberg" },
      { name: "FMS Launch", status: "$70M+ active cases", budget: "40K+ M-code GPS inquiries" },
    ],
    modernization: [
      "Expanding launch provider competition (New Glenn operational)",
      "Reducing launch costs through competition",
      "Increasing launch cadence for PWSA proliferation",
      "Launch range modernization",
    ],
    subOffices: [],
    leadership: [
      { name: "BG Kristin Panzenhagen", title: "PEO" },
    ],
    budgetLinks: [
      { label: "SSC AATS", url: "https://www.ssc.spaceforce.mil/Program-Offices/Assured-Access-to-Space" },
    ],
  },
  {
    id: "peo-bmc3i",
    name: "PEO BMC3I",
    fullName: "Battle Management C3 & Space Intelligence",
    parent: "SSC",
    location: "Los Angeles AFB, CA",
    budget: "Largest SSC PEO",
    budgetNote: "$6.4B earmarked for Long-Range Kill Chains (reconciliation)",
    categories: ["Space C2", "Satellite control", "Kill chains", "SDA data", "SWORD training"],
    keyPrograms: [
      { name: "Satellite Control Network (SCN)", status: "Modernization", budget: "Worldwide antenna network" },
      { name: "Space C2", status: "CSpOC software", budget: "SDA; orbital C2; EW" },
      { name: "Unified Data Library (UDL)", status: "Operational", budget: "SDA data repository" },
      { name: "System Delta 85 (SYD 85)", status: "Stood up Aug 2025", budget: "Kill chain integration" },
      { name: "meshONE-T", status: "9 nodes installed", budget: "Fiber/wireless backbone" },
    ],
    modernization: [
      "Space-based kill chain contributions",
      "SCN modernization for resilience and speed",
      "SWORD training environment scaling",
      "OODA loop compression for space domain",
      "TAP Lab partnership expansion",
    ],
    subOffices: [
      { office: "SYD 85", name: "System Delta 85", desc: "Col. Jason West; BMC3 acquisition-to-operations" },
      { office: "SPD-BA", name: "Battlespace Awareness", desc: "SDA analytics; space intelligence" },
      { office: "SPD-BM", name: "Battle Management", desc: "Operational C2; BMC3 applications" },
      { office: "SPD-SANS", name: "Space Access & Networked Services", desc: "SCN; satellite comms" },
    ],
    leadership: [
      { name: "Shannon Pallone", title: "PEO" },
    ],
    budgetLinks: [
      { label: "SSC BMC3I", url: "https://www.ssc.spaceforce.mil/Program-Offices/Battle-Management-Command-Control-Communications-and-Space-Intelligence" },
    ],
  },
  {
    id: "peo-spacesensing",
    name: "PEO Space Sensing",
    fullName: "Space Sensing",
    parent: "SSC",
    location: "Los Angeles AFB, CA",
    budget: "~$4-5B",
    budgetNote: "Next-Gen OPIR GEO $9.5B total; Polar $5.9B total; Golden Dome",
    categories: ["Missile warning", "Missile tracking", "Environmental monitoring", "Hypersonic tracking", "Golden Dome"],
    keyPrograms: [
      { name: "Next-Gen OPIR GEO", status: "Launch >=Mar 2026", budget: "$9.5B (2 GEO sats)" },
      { name: "Next-Gen OPIR Polar", status: "On track for 2028", budget: "$5.9B (2 polar sats)" },
      { name: "SBIRS", status: "Legacy sustaining", budget: "6 GEO + HEO payloads" },
      { name: "Resilient MW/MT MEO", status: "Early-stage", budget: "Hypersonic tracking" },
      { name: "Golden Dome Space Components", status: "Major FY26 investment", budget: "$4.1B classified+unclassified" },
    ],
    modernization: [
      "Next-Gen OPIR GEO launch acceleration",
      "Multi-orbit missile warning (GEO + MEO + LEO)",
      "Hypersonic tracking: disaggregated sensors",
      "AMTI/GMTI space-based targeting",
      "Golden Dome national missile defense integration",
    ],
    subOffices: [
      { office: "SYD 84", name: "Space-Based MW/MT", desc: "Missile warning and tracking" },
      { office: "SYD 810", name: "Space-Based Sensing & Targeting", desc: "Environmental monitoring; tactical sensing" },
    ],
    leadership: [
      { name: "Col. Leroy Brown", title: "PEO (Jul 2025)" },
    ],
    budgetLinks: [
      { label: "SSC Space Sensing", url: "https://www.ssc.spaceforce.mil/program-offices/space-sensing" },
    ],
  },
  {
    id: "peo-mcpnt",
    name: "PEO MCPNT",
    fullName: "Military Communications & PNT",
    parent: "SSC",
    location: "Los Angeles AFB, CA",
    budget: "~$3B+",
    budgetNote: "ESS $2.8B contract; PTS-G $4B IDIQ; GPS IIIF",
    categories: ["MILSATCOM", "GPS", "PNT", "Strategic SATCOM", "Protected tactical", "Wideband"],
    keyPrograms: [
      { name: "ESS (Evolved Strategic SATCOM)", status: "Boeing $2.8B (2 sats)", budget: "NC3 modernization; ~$12B total" },
      { name: "PTS-G", status: "$4B IDIQ; 5 awardees", budget: "$239M FY26; first launch 2028" },
      { name: "PTS-P Prototype", status: "Launching 2026", budget: "Anti-jam Ka-band" },
      { name: "GPS IIIF", status: "Procurement continuing", budget: "Lockheed Martin" },
      { name: "WGS-11", status: "PTS-P payload; Boeing", budget: "Launching 2026" },
      { name: "EPS-R", status: "Launched Aug 2024; operational", budget: "Arctic MILSATCOM" },
    ],
    modernization: [
      "ESS fielding for NC3 modernization",
      "PTS-P operationalization (anti-jam comms)",
      "PTS-G constellation development (2028 launch)",
      "GPS IIIF and OCX ground system",
      "EPS-R Arctic MILSATCOM integration",
      "Resiliency and anti-jam across all SATCOM tiers",
    ],
    subOffices: [],
    leadership: [
      { name: "Cordell DeLaPena Jr.", title: "PEO" },
    ],
    budgetLinks: [
      { label: "SSC MCPNT", url: "https://www.ssc.spaceforce.mil/Program-Offices/Military-Communications-Positioning-Navigation-Timing" },
    ],
  },
  {
    id: "peo-sdacp",
    name: "PEO SDA&CP",
    fullName: "Space Domain Awareness & Combat Power",
    parent: "SSC",
    location: "Los Angeles AFB, CA / Peterson SFB, CO",
    budget: ">$10B portfolio",
    budgetNote: "60+ programs; Digital Bloodhound $750M; counterspace largely classified",
    categories: ["Space domain awareness", "Counterspace", "Cyber", "SDA radars", "Ground sensors", "NCMC"],
    keyPrograms: [
      { name: "Digital Bloodhound", status: "Cyber defense/offense", budget: "$750M" },
      { name: "UEWR (Early Warning Radars)", status: "Globally distributed", budget: "BMD early warning" },
      { name: "NCMC Modernization", status: "Cheyenne Mountain", budget: "Deep underground facility" },
      { name: "Space Safari", status: "Rapid/affordable prototyping", budget: "COTS spacecraft" },
      { name: "CETIP (Counter-Comms)", status: "Electronic warfare", budget: "$91M" },
    ],
    modernization: [
      "Space domain characterization at scale (AI/ML)",
      "Offensive/defensive counterspace (classified)",
      "NCMC and ground radar modernization",
      "Cyber defense of space systems",
      "Space Safari rapid responsive space",
      "Golden Dome radar/ground station contributions",
    ],
    subOffices: [
      { office: "Ground Radar", name: "Ground Radar Division", desc: "SSN radars; UEWR; COBRA DANE" },
      { office: "Optical/RF", name: "Optical & Passive RF", desc: "Ground-based optical/RF monitoring" },
      { office: "Combat Systems", name: "Combat Systems Division", desc: "Counter-communications; counterspace" },
      { office: "Cyber Ops", name: "Cyber Operations", desc: "Digital Bloodhound; cyber defense" },
      { office: "Space Safari", name: "Space Safari", desc: "Rapid acquisition; COTS spacecraft" },
    ],
    leadership: [],
    budgetLinks: [
      { label: "SSC SDA&CP", url: "https://www.ssc.spaceforce.mil/Program-Offices/Space-Combat-Power" },
    ],
  },
  {
    id: "peo-otti",
    name: "PEO OTTI",
    fullName: "Operational Test & Training Infrastructure",
    parent: "SSC",
    location: "Los Angeles AFB, CA",
    budget: "Included in SSC",
    budgetNote: "SWORD training environment; OTA awarded Sep 2025",
    categories: ["Test infrastructure", "Training", "SWORD", "Space warfighter readiness"],
    keyPrograms: [
      { name: "SWORD", status: "Scaling to enterprise 2026", budget: "Synthetic training environment" },
      { name: "Space Test", status: "OTA awarded Sep 2025", budget: "Software Acquisition Pathway" },
    ],
    modernization: [
      "SWORD training environment enterprise scaling",
      "Integrated test and training capabilities",
      "Software Acquisition Pathway adoption",
    ],
    subOffices: [],
    leadership: [
      { name: "Col. Corey Klopstein", title: "PEO / SYD 81 Commander" },
    ],
    budgetLinks: [],
  },
  {
    id: "sda",
    name: "SDA",
    fullName: "Space Development Agency",
    parent: "U.S. Space Force",
    location: "Washington, D.C. / Grand Forks AFB, ND",
    budget: "~$4.3B",
    budgetNote: "T3 Tracking $3.5B awarded Dec 2025; 72 satellites",
    categories: ["Proliferated LEO constellation", "PWSA", "Missile tracking", "Optical links", "Transport layer"],
    keyPrograms: [
      { name: "PWSA Tranche 1", status: "Launching Sep 2025 – mid-2026", budget: "154 transport + tracking sats" },
      { name: "PWSA Tranche 2", status: "Development; launch 2027", budget: "Transport + 54 tracking sats" },
      { name: "PWSA T3 Tracking", status: "$3.5B awarded Dec 2025", budget: "72 satellites; 4 vendors" },
      { name: "Tranche 0", status: "Operational since 2023", budget: "28 transport + 4 tracking demo" },
      { name: "Airborne Optical Comms", status: "RFI Jan 2026", budget: "Aircraft-to-PWSA link" },
    ],
    modernization: [
      "T1 launch campaign (Sep 2025 – early 2027)",
      "T2 development and launch preparation",
      "T3 contract execution (72 tracking + transport sats)",
      "Iron Dome for America architecture contributions",
      "Airborne optical terminal integration",
    ],
    subOffices: [
      { office: "Transport Layer", name: "Transport Layer", desc: "Low-latency military data relay; optical inter-satellite links" },
      { office: "Tracking Layer", name: "Tracking Layer", desc: "Global missile warning/tracking; hypersonic" },
      { office: "Battle Mgmt Layer", name: "Battle Management Layer", desc: "Architecture tasking; kill chain closure" },
      { office: "Custody Layer", name: "Custody Layer", desc: "24/7 target custody for engagement" },
      { office: "Navigation Layer", name: "Navigation Layer", desc: "GPS-independent optical ranging" },
    ],
    leadership: [
      { name: "Dr. Gurpartap 'GP' Sandhoo", title: "Acting Director" },
    ],
    budgetLinks: [
      { label: "SDA Website", url: "https://www.sda.mil" },
    ],
  },
];
